name: Toot Scheduler

on:
  schedule:
    # Run this workflow every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  toot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt

      - name: Toot
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: |
          python toot.py
