name: Toot Scheduler

on:
  schedule:
    # Run this workflow every hour
    - cron: '0 * * * *'

jobs:
  toot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Mastodon.py

      - name: Toot
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: |
          python toot.py
